# Generated by Django 5.1 on 2024-11-24 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegetracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
