# Generated by Django 5.1 on 2024-12-20 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegetracker', '0002_smartcollege_enrollment_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipcode', models.CharField(max_length=20)),
                ('cipdesc', models.TextField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='collegetracker.college')),
            ],
        ),
    ]
