# Generated by Django 5.1 on 2024-12-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegetracker', '0003_collegeprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeprogram',
            name='UNITID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
