# Generated by Django 5.1 on 2026-02-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegetracker', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='application_deadline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
