# Generated by Django 5.1 on 2026-02-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegetracker', '0010_college_application_deadline_college_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='college_images/'),
        ),
    ]
