# Generated by Django 5.1 on 2026-02-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegetracker', '0011_college_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='control',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='hbcu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='college',
            name='hsi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='college',
            name='locale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='men_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='college',
            name='relaffil',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='women_only',
            field=models.BooleanField(default=False),
        ),
    ]
