# Generated by Django 5.1 on 2026-02-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegetracker', '0012_college_control_college_hbcu_college_hsi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='avg_net_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='grad_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='loan_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
