# Generated by Django 5.1 on 2026-02-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegetracker', '0013_college_avg_net_price_college_grad_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='carnegie_classification',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='is_distance_education',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='college',
            name='is_open_admission',
            field=models.BooleanField(default=False),
        ),
    ]
