# Generated by Django 5.1 on 2026-02-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegetracker', '0014_college_carnegie_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='retention_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='student_faculty_ratio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartcollege',
            name='avg_net_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartcollege',
            name='grad_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartcollege',
            name='retention_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartcollege',
            name='student_faculty_ratio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
