# Generated by Django 5.1 on 2024-12-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegetracker', '0014_friendship_status_alter_friendship_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
