# Generated by Django 5.1 on 2026-02-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegetracker', '0015_college_retention_rate_college_student_faculty_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='top_major',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartcollege',
            name='top_major',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
