# Generated by Django 5.1 on 2026-02-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegetracker', '0016_college_top_major_smartcollege_top_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sat_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
