# Generated by Django 5.1 on 2026-02-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegetracker', '0018_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
