# Generated by Django 5.1 on 2026-02-20 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegetracker', '0019_college_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='associated_college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='collegetracker.college'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('college_staff', 'College Staff'), ('admin', 'Administrator')], default='student', max_length=20),
        ),
    ]
