# Generated by Django 5.1 on 2026-02-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegetracker', '0022_directmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_eligible_to_claim',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('friend_request', 'Friend Request'), ('accepted_request', 'Accepted Request'), ('direct_message', 'Direct Message')], max_length=20),
        ),
    ]
