# Generated by Django 5.1 on 2026-02-22 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegetracker', '0024_directmessage_attachment_alter_directmessage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interviewed', 'Interviewed'), ('qualified', 'Qualified'), ('enrolled', 'Enrolled'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='collegetracker.college')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('college', 'student')},
            },
        ),
    ]
