# Generated by Django 5.1 on 2026-02-23 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegetracker', '0027_directmessage_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='collegetracker.college'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_announcement',
            field=models.BooleanField(default=False),
        ),
    ]
