# Generated by Django 5.1 on 2026-02-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegetracker', '0028_post_college_post_is_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('acceptance', '🎉 Acceptance Stories'), ('essay_help', '✍️ Essay Help'), ('campus_tours', '🏫 Campus Tours'), ('financial_aid', '💰 Financial Aid'), ('test_prep', '📚 Test Prep'), ('advice', '💡 Advice'), ('general', '💬 General')], default='general', max_length=20),
        ),
    ]
