# Generated by Django 5.1 on 2026-03-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegetracker', '0029_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='verified_picture',
            field=models.BooleanField(default=False),
        ),
    ]
