# Generated by Django 5.1 on 2026-03-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegetracker', '0031_user_advisor_bio_user_hourly_rate_user_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_selected_role',
            field=models.BooleanField(default=False),
        ),
    ]
