# Generated by Django 5.1 on 2026-04-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegetracker', '0034_service_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='lower_earnings_indicator',
            field=models.BooleanField(default=False, help_text='Flag for institutions where grads earn less than HS grads'),
        ),
        migrations.AddField(
            model_name='college',
            name='median_earnings_4yr',
            field=models.IntegerField(blank=True, help_text='Median earnings 4 years after graduation', null=True),
        ),
        migrations.AddField(
            model_name='collegeprogram',
            name='median_earnings',
            field=models.IntegerField(blank=True, help_text='Median earnings for this program 4 years after graduation', null=True),
        ),
        migrations.AddField(
            model_name='collegeprogram',
            name='national_median',
            field=models.IntegerField(blank=True, help_text='National median earnings for this field of study', null=True),
        ),
    ]
