# Generated by Django 5.1 on 2026-04-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegetracker', '0035_college_lower_earnings_indicator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='UNITID',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='collegeprogram',
            name='UNITID',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collegeprogram',
            name='cipcode',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='collegeprogram',
            name='creddesc',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
