# Generated by Django 5.1 on 2026-05-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegetracker', '0038_advisoravailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('target_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('ad_type', models.CharField(choices=[('university_spotlight', 'University Spotlight'), ('advisor_showcase', 'Advisor Showcase'), ('other', 'Other Advertisement')], default='university_spotlight', max_length=50)),
                ('pricing_model', models.CharField(choices=[('flat_rate', 'Flat Rate'), ('cpc', 'Cost Per Click (CPC)'), ('cpm', 'Cost Per Mille (CPM)')], default='flat_rate', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('clicks', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('metric_acceptance_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('metric_sat_range', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
